//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoodsCompany.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Company
    {
        public int Id { get; set; }
        public string CompanyName { get; set; }
        public int StaticCode { get; set; }
        public string Address { get; set; }
        public string TelephoneNumber { get; set; }
        public int PriceListId { get; set; }
        public int MarketingDepartmentId { get; set; }
        public int SupervisorId { get; set; }
    
        public virtual MarketingDepartment MarketingDepartment { get; set; }
        public virtual PriceList PriceList { get; set; }
        public virtual Supervisor Supervisor { get; set; }
    }
}
