//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoodsCompany.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GoodsEntities : DbContext
    {
        private static Model.GoodsEntities _context = new Model.GoodsEntities();
        public GoodsEntities()
            : base("name=GoodsEntities")
        {
        }

        public static Model.GoodsEntities GetContext()
        {
            if (_context == null)
                _context = new Model.GoodsEntities();
            return _context;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Company> Company { get; set; }
        public virtual DbSet<Good> Good { get; set; }
        public virtual DbSet<GoodsGroup> GoodsGroup { get; set; }
        public virtual DbSet<MarketingDepartment> MarketingDepartment { get; set; }
        public virtual DbSet<PriceList> PriceList { get; set; }
        public virtual DbSet<Supervisor> Supervisor { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
