//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoodsCompany.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class MarketingDepartment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MarketingDepartment()
        {
            this.Company = new HashSet<Company>();
        }
    
        public int Id { get; set; }
        public string TelephoneNumber { get; set; }
        public string ContactPerson { get; set; }
        public int SupervisorId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Company> Company { get; set; }
        public virtual Supervisor Supervisor { get; set; }
    }
}
